
{
    'name': 'Agricultural Export Core',
    'version': '19.0.1.0.0',
    'summary': 'End-to-end agricultural export workflow (farm → packing → shipment → invoice)',
    'category': 'Inventory',
    'author': 'NextGen Systems',
    'license': 'LGPL-3',
    'depends': ['base','purchase','stock','mrp','sale','account','uom','mail','web'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/menu.xml',
        'views/farm_views.xml',
        'views/crop_views.xml',
        'views/evaluation_views.xml',
        'views/production_views.xml',
        'views/shipment_views.xml',
        'reports/traceability_report.xml',
        'wizard/traceability_wizard_views.xml',
        'demo/demo.xml',
    ],
    'installable': True,
    'application': True,
}
