# -*- coding: utf-8 -*-
{
    "name": "Export Shipment",
    "version": "19.0.1.0.0",
    "category": "Inventory",
    "summary": "Manage export shipments and containers",
    "description": "This is an autogenerated advanced module scaffold.",
    "author": 'NextGen Systems',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base", "sale_management", "stock", "mail", "mrp", "accountant"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/export_shipment_views.xml",
        "views/menu.xml",
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}